### ISSUE TITLE
A bug in the train_jhmdb.m

### ISSUE THREAD

**Issue by iveel** [gkioxari/ActionTubes#3]
train_jhmdb.m: line 140, 141
 [~, ~, dups] = intersect(caches{j}.keys, keys{j}, 'rows');
 assert(isempty(dups));

Above two lines always gives assertion error. Do you think these lines are necessary as the duplicated entries are already checked in the "get_negative_features" function at line 133.

**Comment by gkioxari** [comment]
They might not be necessary, as you point out, but it would be good to see why the assertion fails. Is dups non empty for you?

**Comment by iveel** [comment]
Because, in the first loop (as caches are initialized empty at line 111) dups is always empty.

**Comment by gkioxari** [comment]
Then I would recommend adding an if statement that would not make it crash in the case that the cache.keys is empty.
